### ISSUE TITLE
Crashing on CreateMove hook

### ISSUE THREAD

**Issue by Nikkod** [MarkHC/CSGOSimple#116]
I can inject in the lobby and be fine but once I go into a game and a few seconds pass csgo will crash.
It has also crashed when I try to open console after injecting.

![screenshot 108](https://user-images.githubusercontent.com/6183095/46575456-2fc5ab00-c96a-11e8-884b-9c1d7a463a01.png)

**Comment by anarh1st47** [comment]
Indexes totally outdated

**Comment by Nikkod** [comment]
I updated the indexes but now I have arrived with another problem.

![screenshot 109](https://user-images.githubusercontent.com/6183095/46576808-34995780-c988-11e8-8584-720a9e0e241d.png)

**Comment by Nikkod** [comment]
Thank you
