### ISSUE TITLE
[VS2017] MM_store_ps is undefined

### ISSUE THREAD

**Issue by a09hopper** [MarkHC/CSGOSimple#13]
So Line 227 in Vector.hpp is undefined however if I comment it out it will build but not run. I have installed DirectX SDK and I am using 2017 Visual studio so is it something that needs 2013/2012 to build? or am I being dumb?

**Comment by MarkHC** [comment]
It's probably something related to VS2017 as I've never seen that problem before.

I use VS 2015, but the project should work on older versions as well (provided you do some changes on the project settings).

**Comment by a09hopper** [comment]
thanks. Downloading VS 2015 now

**Comment by pGav** [comment]
Add `#include <intrin.h>` to Vector.hpp in VS2017.

**Comment by PhilipKDick** [comment]
including header emmintrin.h to Vector.hpp will fix this problem

**Comment by a09hopper** [comment]
The full release of visual studio 2017 has now fixed this problem. Thanks for all suggestions though, I kind of went out of the scene for a while.
