### ISSUE TITLE
ImGui Drawing issue

### ISSUE THREAD

**Issue by a09hopper** [MarkHC/CSGOSimple#15]
When I use your hack and inject the ImGui bit only draws on the main menu, buy menu and console. Any ideas on how to fix?

**Comment by themaxtwo2** [comment]
cl_drawfps 0

**Comment by MarkHC** [comment]
Set the D3DRS_COLORWRITEENABLE render state.

https://msdn.microsoft.com/en-us/library/windows/desktop/bb172599(v=vs.85).aspx
http://www.unknowncheats.me/forum/counterstrike-global-offensive/154776-directx-issue-2.html
