### ISSUE TITLE
C_BaseEntity does not contain a set of methods!

### ISSUE THREAD

**Issue by GabCoder** [MarkHC/CSGOSimple#18]
I have one trouble with SourceEngine::C_BaseEntity, i have object of C_BaseEntity and i want to get a **teamnum** of this obj, but it's impossible, because C_BaseEntity doesn't contains any methods... 

What i must do to get teamnum from C_BaseEntity? =(
You can help me a lot. thx

**Comment by themaxtwo2** [comment]
You are obviously just pasteing and have no clue what you are doing so I just go check this file and learn the language please.

https://github.com/MarkHC/CSGOSimple/blob/b92d5ad778d04b8ffe7ac65f911647b635397486/CSGOSimple/CSGOStructs.hpp

if you actually knew what you where doing you would see that C_BaseEntity is a enum in this SDK.

**Comment by MarkHC** [comment]
C_BaseEntity is used just for "compatibility" with some of the Source Engine functions that expect a C_BaseEntity pointer as parameter. It is not meant to be used on your own code.

Use C_CSPlayer, or IClientEntity instead. 

If some function expects a C_BaseEntity pointer, you can just do a cast.
