### ISSUE TITLE
[VS 2017]  Can not open 'd3d9x.h' - no such file or directory

### ISSUE THREAD

**Issue by bokatianti** [MarkHC/CSGOSimple#20]
Its just that and 4 warnings when i build it in VS2017.

**Comment by themaxtwo2** [comment]
what are the warnings? 

    On Friday, March 17, 2017 12:24 PM, bokatianti <notifications@github.com> wrote:
 

 Its just that and 120 warnings when i build it in VS2017.—

**Comment by bokatianti** [comment]
Now i only have the error of cannot include "d3dx9.h"

**Comment by Skyline23** [comment]
just google it.

**Comment by a09hopper** [comment]
You need to download the DirectX SDK from Microsoft and include it in your solution and include the lib files in linker. Just search up a directx tutorial on youtube and follow how to include directx
