### ISSUE TITLE
Update Signatures please!

### ISSUE THREAD

**Issue by Krouzu** [MarkHC/CSGOSimple#22]

**Comment by themaxtwo2** [comment]
Learn how to reverse and this wont be a problem, Quit feeding off others and learn to do it yourself.

**Comment by hervvv** [comment]
Changing the sig at [CSGOSimple/SourceEngine/SDK.cpp#L108](https://github.com/MarkHC/CSGOSimple/blob/b0473c0d5e5d3e467414e825d44dcf5e9b8b0c79/CSGOSimple/SourceEngine/SDK.cpp#L108) to `8B 0D ? ? ? ? 8B 01 5D FF` resolves the crashes. I've noticed some some visual glitching by ImGUI when drawing ESP, don't know the solution there.

**Comment by baarsik** [comment]
ESP is fixed by getting rid of D3D drawings and hooking PaintTraverse directly. Will probably upload later.

**Comment by MarkHC** [comment]
No.
