### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by Tulkin123** [MarkHC/CSGOSimple#25]
It's always crashing. anyone knows a fix?

**Comment by skrrtskrrt** [comment]
Update your clientmode here's some c+p

IClientMode* Interfaces::ClientMode()
    {
        if(!m_pClientMode) {
            auto uAddress = *(DWORD*)(Utils::FindSignature(XorStr("client.dll"), XorStr("8B 0D ? ? ? ? 8B 01 5D FF")) + 2);
            m_pClientMode = *(IClientMode**)(uAddress);
        }
        return m_pClientMode;
    }
}
