### ISSUE TITLE
Changing the color code will make stuff invisable

### ISSUE THREAD

**Issue by Logxn** [MarkHC/CSGOSimple#34]
So for example you have glow activated, and you change the color code in the menu, the glow will just be invisible.

Same for esp boxes, wireframe etc.

**Comment by MarkHC** [comment]
How are you trying to change it? The last 2 digits (FF) are the Alpha, make sure they are not set to 00.

https://streamable.com/5ec1m

**Comment by Logxn** [comment]
Aight, my bad sorry :p
