### ISSUE TITLE
ESP

### ISSUE THREAD

**Issue by bighaxor** [MarkHC/CSGOSimple#36]
http://i.imgur.com/3infHOR.png they resize weirdly also if you deselect glow on dropped items and there were already dropped items with glow they will still have glow on them

**Comment by bighaxor** [comment]
I also realised if dropped items with glow won't take the glow away if you turn off glow it will only apply newly dropped items

**Comment by czvpka** [comment]
The boxes bug depends on that, the box size and pisition is based on hitbox location, but the hitboxes aren't readed well from some distance and angle, so this bug happens (i think). Let @MarkHC look deeper into it and I think he will repair it :)

**Comment by bighaxor** [comment]
I've heard there are some fixes for it and theres a way to make it so the box doesnt change size depending on your viewangles

**Comment by bighaxor** [comment]
The glow doesn't deactivate properly & esp resizes weirdly
