### ISSUE TITLE
Black chams

### ISSUE THREAD

**Issue by czvpka** [MarkHC/CSGOSimple#38]
http://i.imgur.com/HSRhvXy.png
Why it is like that? Its my video settings:
http://i.imgur.com/DteW7eI.png

**Comment by bighaxor** [comment]
Download the updated version the file paths are wrong for the cham styles on that one

**Comment by czvpka** [comment]
okay, thanks!

**Comment by czvpka** [comment]
all is working, when re-downloaded chams.cpp and chams.hpp, closed :]
