### ISSUE TITLE
Source files could do with being organized in to folders

### ISSUE THREAD

**Issue by lukeramsden** [MarkHC/CSGOSimple#42]
Very difficult to manage right now, just a big list of files.

**Comment by tehuno** [comment]
what are you talking about

**Comment by lukeramsden** [comment]
The solution, when opened in Visual Studio, currently is just a big list of files for CSGO Simple, would be more organized with some folders. I'd be happy to make a PR for it.

**Comment by wi1h** [comment]
I think he's talking about the filters in the project, not the actual
folder structure.

**Comment by tehuno** [comment]
Luke there is literally a button you press in visual studio to change the organization to match the folders... why are you posting so many issues on here when this is not an issue with this code.

**Comment by MarkHC** [comment]
I use folder structure on VS, not the filters. But i guess you're right.

**Comment by lukeramsden** [comment]
@MarkHC Ahh OK that makes sense.

**Comment by MarkHC** [comment]
This has been "fixed" on https://github.com/MarkHC/CSGOSimple/commit/a6da71305f2d2dd0d04ae95676c92dcf2ea965ec

**Comment by lukeramsden** [comment]
Nice work
