### ISSUE TITLE
Weapon Chams

### ISSUE THREAD

**Issue by lukeramsden** [MarkHC/CSGOSimple#45]
Wireframe/flat/glass on weapons as well as hands.

**Comment by MarkHC** [comment]
Yes, the empty space to the side of the "arms" groupbox was for the weapon chams box, but i never got around to adding it.

**Comment by bighaxor** [comment]
If you're adding weapon chams add hand chams aswell

**Comment by lukeramsden** [comment]
@bighaxor We already have them right?

**Comment by bighaxor** [comment]
No it currently has full arm chams but theres a way to do arm & hand chams so your arms a dif color/texture than your hand

**Comment by wi1h** [comment]
I mean, all of this is nice and all, and maybe it's just me, but wouldn't it be better for this to just be a base like it has been?

Sure, have basic chams, but fully featuring it strays away from the original purpose of this project.

But hey, it's not my project I guess.

**Comment by bighaxor** [comment]
Chams are very basic lol

**Comment by lukeramsden** [comment]
Yeah I agree to be honest, lets just add nice-looking visual stuff and menu, and let people build legitbot/ragebot/skin-changer/etc on their own.

**Comment by bighaxor** [comment]
The stuff thats already in just needs to become flawless so the esp doesnt get affected by viewangles dynamic box is normal proper cham xqz

**Comment by bighaxor** [comment]
Everyone just needs to perfect the current features in the cheat adding weapon chams doesn't really ruin the simple base
