### ISSUE TITLE
pEntity->GetBonePos()

### ISSUE THREAD

**Issue by czvpka** [MarkHC/CSGOSimple#52]
The function, that I mentioned, ALWAYS returns `Vector(0, 0, 0)`. But when I use `GetEyePos()` it returns correct values. Someone know what can happen that? Please reply.

**Comment by MarkHC** [comment]
Is pEntity the local player? Maybe post some of your code. 

GetEyePos is completely independent of bone positions though, it is just the player origin + [0,0,z] with z being the height of the player head (IIRC 72 when standing).

**Comment by hsurk** [comment]
Think it's just `return Vector{ boneMatrix[bone].at(0) };` that doesn't work? When doing it the classical way, using both indexes of the matrix it works.

**Comment by MarkHC** [comment]
I see. Turns out VMatrix is column-major. I was thinking it was Row-Major when i wrote the `at` method.

Should be fixed now. https://github.com/MarkHC/CSGOSimple/commit/30c06079ba66886dec6451edb35bf4d058fd73be

**Comment by bighaxor** [comment]
close @MarkHC
