### ISSUE TITLE
Error: Symbol file not found

### ISSUE THREAD

**Issue by BobNobody** [MarkHC/CSGOSimple#55]
Sometimes when im aimbotting, it crashes
Exception thrown at 0x39EFEFF6 (csgosimple.dll) in csgo.exe: 0xC0000005: Access violation reading location 0x00000020.

It says 
No symbol file loaded for csgosimple.dll

Any ideas im rather new to programming and such and im kinda lost at this

**Comment by wi1h** [comment]
What line does it crash on?

**Comment by BobNobody** [comment]
Instead of showing me the line where it broke, like im used to, rather it opens a window with the aforementioned no symbol file loaded message. I have a hunch that it has to do with my target selection, as it happens in particular when I enable a check to see if the enemy is visible, and no one is visible. Thanks for the fast reply by the way

**Comment by BobNobody** [comment]
I need to test a bit more, ill get back to you with more info

**Comment by wi1h** [comment]
Hmm, you're compiling in debug with symbols enabled in your compiler settings, right?

**Comment by wi1h** [comment]
Also, considering that this source doesn't have any sort of aim assitance, this is probably the wrong place to ask for help.

**Comment by BobNobody** [comment]
Alright that was disgustingly noobish fml

**Comment by BobNobody** [comment]
At least now I should be able to debug properly
