### ISSUE TITLE
Setting viewangles clientside?

### ISSUE THREAD

**Issue by Lukez3218** [MarkHC/CSGOSimple#56]
I just got into internals developing and I am trying to write a super simple aimbot, and I managed to set the viewangles "serverside" by using "cmd->viewangles = someangle", the problem is I can't seem to find a way to set the viewangle "clientside". Any help?

**Comment by wi1h** [comment]
Look up bSendPacket. Also, not the place to ask for this kind of thing (aim isn't supported in this base and is therefore not an issue with said base).

**Comment by Giiraffe** [comment]
IVEngineClient#SetViewAngles
https://github.com/MarkHC/CSGOSimple/blob/master/CSGOSimple/valve_sdk/interfaces/IVEngineClient.hpp#L84

Pass it 'cmd->viewangles' after you have updated it to "some angle"

**Comment by Lukez3218** [comment]
@Giiraffe Thanks, exactly what I was looking for!
@wi1h Yeah, I know it's not an issue with this base, I was just looking for somebody to point me in the right direction since as I said I'm new to internals. I'm sorry if I shouldn't have posted here.

**Comment by Giiraffe** [comment]
No worries, Glad I could help.
