### ISSUE TITLE
How do i run this hack?

### ISSUE THREAD

**Issue by carsonoreilly** [MarkHC/CSGOSimple#6]
Im pretty sure I have to use VS 2015 but how do I get this code into VS 2015? And run it for it to work in CSGO

**Comment by carsonoreilly** [comment]
nvm i have it in my visual studios now, should I run it after I open CSGO? and is it still undetected?

**Comment by carsonoreilly** [comment]
when i try to run the code it says theres 4 errors, all of them saying : Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory

**Comment by carsonoreilly** [comment]
can i use this with directx12?

**Comment by MarkHC** [comment]
You dont have the DirectX 9 SDK installed on your machine.

**Comment by carsonoreilly** [comment]
i installed it but it still doesnt work, could u plz make a tutorial?

**Comment by P4R4DiSi4C** [comment]
Hello MarkHC,
Could you point me where is the file I have to insert the updated offsets ?

Thanks

**Comment by Xetrics** [comment]
@P4R4DiSi4C this uses a netvar manager, there are no offsets.
