### ISSUE TITLE
Trying to make no scope

### ISSUE THREAD

**Issue by xbRead** [MarkHC/CSGOSimple#60]
> static auto pHud = g_CVar->FindVar("cl_drawhud");
 void Visuals::Misc::RenderNoScope()
 {
	 if (g_LocalPlayer->m_bIsScoped)
	 {
		 pHud->SetValue(0);

		 int w, h;

		 g_EngineClient->GetScreenSize(w, h);

		 g_VGuiSurface->DrawSetColor(0, 0, 0, 255);

		 int cx = w / 2;
		 int cy = h / 2;

		 g_VGuiSurface->DrawLine(cx - 200, cy, cx + 200, cy);
		 g_VGuiSurface->DrawLine(cx, cy - 200, cx, cy + 200);
	 }

	 if (g_LocalPlayer->m_bIsScoped)
	 {
		 pHud->SetValue(1);
	 }

 }

That's my code and the error i get is : Severity	Code	Description	Project	File	Line	Suppression State
Error	C3867	'C_BasePlayer::m_bIsScoped': non-standard syntax; use '&' to create a pointer to member	CSGOSimple	C:\Users\i\Desktop\muhai_private\CSGOSimple\features\visuals.cpp	350	
I tried using  if (g_LocalPlayer && m_bIsScoped) but i still get errors please help thanks.

**Comment by Skyline23** [comment]
In PaintTraverse
```
if(!strcmp("HudZoom", Interfaces.pPanel->GetName(vguiPanel)))
        return;
```
