### ISSUE TITLE
Hooking NoRecoil

### ISSUE THREAD

**Issue by FiXionSvK** [MarkHC/CSGOSimple#63]
Hello, so I recently downloaded MarkHC's CSGOSimple.

I tried making simple NoRecoil
aimbot.hpp
`class C_BasePlayer;
class CUserCmd;`

aimbot.cpp
`#include "valve_sdk\csgostructs.hpp"
#include "helpers\math.hpp"

class aimbot
{
	void aimbot::norecoil(CUserCmd* cmd)
	{
	QAngle data = g_LocalPlayer->m_aimPunchAngle();
	cmd->viewangles -= data * 2;							// get aimpunchangle & viewangles and double it.
	Math::NormalizeAngles(cmd->viewangles);
	}
};`
But I cant hook it properly, someone knows the answer?
Im newbie in csgo hacking so please excuse me x)

**Comment by bighaxor** [comment]
First of all recoil compensation isn't a hook and you can do it in 3 lines

**Comment by bighaxor** [comment]
You don't hook "No recoil" it's not a hook just a function and it's very easy to do

**Comment by FiXionSvK** [comment]
Then tell me how please ;_;

**Comment by FiXionSvK** [comment]
update: I finally hooked it

**Comment by bighaxor** [comment]
not a hook & close this

**Comment by MarkHC** [comment]
You should also call `Math::ClampAngles` before you get yourself untrusted.
