### ISSUE TITLE
Revolver showing as deagle

### ISSUE THREAD

**Issue by xbRead** [MarkHC/CSGOSimple#67]
this.
https://i.imgur.com/ZNa5CCF.jpg
Also, why is the E uppercased checked through the code saw no way to change it there prob is but I might just be dumb.

**Comment by LeagueRaINi** [comment]
did u pull this update?
https://github.com/MarkHC/CSGOSimple/commit/552c2758e9789544b088d3cb288a45deed4b98f5

**Comment by xbRead** [comment]
Yes, I used that update still shows as a deagle.

**Comment by LeagueRaINi** [comment]
the guy that updated the item definition enum fucked up, i already made a pull request for an updated one

**Comment by xbRead** [comment]
Thanks.
