### ISSUE TITLE
Broken filter vcxproj.filters file

### ISSUE THREAD

**Issue by ghost** [MarkHC/CSGOSimple#77]
I noticed while including a .hpp file I had created in the features folder, I didn't have to add "features/" inside the include. I looked into it some more and it turns out that everything I create gets put into the root directory of my project for what ever reason. It also seems that the utilities that are supposed to be in the helpers folder are just in the root directory according to Visual Studio (2017) as well. I did some looking around and it seems like the vcxproj.filters file is broken. I've tried fixing it multiple times with no luck.
Anyone have a fixed version or willing to fix it?

EDIT: Here is what Visual Studio shows inside the workspace (http://i.imgur.com/nzzWqbc.png) which I know is incorrect by just looking at the folders/files inside the project's directory.

EDIT 2: I've fixed most of the issue(s), everything is displayed correctly in Visual Studio, all of the folders have their correct name(s), but when I create a .cpp file or .hpp file in lets say the features folder, it still puts it in the root directory of the project. If anyone wants the semi-fixed vcxproj.filters file here it is: https://pastebin.com/raw/mGLX7SQS

**Comment by eue398** [comment]
You realise the folders in vs aren't actual directories?

**Comment by DarkAussieYT** [comment]
they are filters
