### ISSUE TITLE
I cannot get the injector to work.

### ISSUE THREAD

**Issue by LayersRares** [MarkHC/CSGOSimple#81]
Hello, I wanted to start making internals, as so far I've only made an external. A lot of people recommended I use your base and I thought I would use it to learn the basics and get started, but I'm pretty sure it's outdated so I wanted to debug it. But when I run the injector using VS's debugger it can't find the DLL. When I run the injector directly it just says "Failed to inject DLL." Is there something I'm missing or should I just get another injector?

**Comment by LayersRares** [comment]
Nevermind, I'll just use a different one.

**Comment by M-T3K** [comment]
The Injector is working perfectly fine, at least for me. Make sure that the DLL is called "csgosimple.dll" without the "" and ensure that it is on the same folder as the Injector.  Anyways this is an open source Load Library Injector. It will probably get detected soon, if it isn't already. You should try to make your own!
