### ISSUE TITLE
Chams not working when behind the wall.

### ISSUE THREAD

**Issue by m0L3cuL3** [MarkHC/CSGOSimple#91]
Chams works perfectly fine but when the player goes behind a wall it doesn't shows up. I didn't checked the box "Visible only" if you're wondering. Thanks in advance :).

**Comment by KiritsuXZero** [comment]
If behind wall ur chams using ignorz?

**Comment by m0L3cuL3** [comment]
What's ignorz?

**Comment by KiritsuXZero** [comment]
If u chams behind wall using igonre-Z

**Comment by m0L3cuL3** [comment]
nope it's not using ignore-Z.

**Comment by KiritsuXZero** [comment]
I talk use ignore-Z

**Comment by KiritsuXZero** [comment]
If player behind wall

**Comment by m0L3cuL3** [comment]
Thanks very much it worked :))
