### ISSUE TITLE
Radar Hack

### ISSUE THREAD

**Issue by m0L3cuL3** [MarkHC/CSGOSimple#93]
I can't transfer my radar hack in CSGOSimple. Need help. Thanks in advance :)

**Comment by xbRead** [comment]
Nice. Mind leaving some code and the problems you're experiencing?

**Comment by m0L3cuL3** [comment]
// Radar
			if (Menu::Window.VisualsTab.OtherRadar.GetState())
			{
				DWORD m_bSpotted = NetVar.GetNetVar(0x839EB159);
				*(char*)((DWORD)(pEntity) + m_bSpotted) = 1;
			}

I got this from a ayyware paste i made (WHIP AYYWARE)
how do I transfer this? Thanks in advance

**Comment by ZorCoder** [comment]
@m0L3cuL3  What you're doing is not "learning" if you were to look into the SDK a little bit more you could've figured it out with 1 of your hands up your ass.

Please redefine learning for yourself.

**Comment by anarh1st47** [comment]
@m0L3cuL3

```
void Visuals::Player::InGameRadar() {
    esp_ctx.pl->m_bSpotted() = true;
}
```

hkPaintTraverse(esp section):
```
Visuals::Player::InGameRadar();
```
csgostructs:
```
NETVAR(bool,				  m_bSpotted, "DT_BaseEntity", "m_bSpotted");
```

But i agreeed with @ZorCoder

**Comment by m0L3cuL3** [comment]
Thanks @anarh1st47 . I also agree with @ZorCoder that's why i bought some cpp books.
