### ISSUE TITLE
m_fCameraInThirdPerson in CInput

### ISSUE THREAD

**Issue by andrevanduin** [MarkHC/CSGOSimple#98]
The offset of m_fCameraInThirdPerson is no longer correct.

**Comment by anarh1st47** [comment]
Looks like valve add 8 bytes to cinput:
https://www.unknowncheats.me/forum/1837162-post14.html

**Comment by andrevanduin** [comment]
Thanks for the comment! You solved my problem. Maybe someone should open A pull request to add the extra 8 bytes?

**Comment by anarh1st47** [comment]
@andrevanduin @MarkHC #99
